In [1]:
import numpy as np

<h1>np.arange vs np.linspace</h1>

<h1>ndarray vs .array([...]) vs array([...])</h1>

<h1>math va moghaiese on ndarray</h1>

In [21]:
%timeit 2 * np.arange(10000)

24.2 μs ± 631 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [8]:
2 * list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
%timeit list( map( lambda x:2 * x, list(range(10000))) )

1.48 ms ± 487 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [23]:
%timeit [2*member for member in range(10000)]

821 μs ± 282 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [35]:
0 <= np.arange(10)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [36]:
np.arange(10) < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

<h1>arrays attributes</h1>

In [31]:
my_array = np.array([[1, 2],
                    [3, 4]])

In [32]:
my_array.shape

(2, 2)

In [33]:
my_array.ndim

2

In [34]:
my_array.dtype

dtype('int64')

<h1>create ndarray</h1>

In [27]:
import numpy as np

In [5]:
np.zeros((2,2,2))

3

In [6]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [7]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [10]:
np.full((2,2), 5)

array([[5, 5],
       [5, 5]])

In [14]:
lst = [1, 2]
tpl = (1, 2)
dct = {1:11, 2:12}
st = {1, 2}

In [15]:
np.array(lst)

array([1, 2])

In [16]:
np.array(tpl)

array([1, 2])

In [21]:
np.array(dct)

array({1: 11, 2: 12}, dtype=object)

In [22]:
np.array(st)

array({1, 2}, dtype=object)

In [50]:
np.array('nima')

array('nima', dtype='<U4')

In [52]:
sample = np.array([1,2])

In [54]:
np.zeros_like(sample)

array([0, 0])

<h1>ndarray of 0=dim and shape=()</h1>

<h1>numpy.ndarray.item()</h1>

In [35]:
scalar = np.array('nima')

In [36]:
scalar

array('nima', dtype='<U4')

In [37]:
scalar.item()

'nima'

In [38]:
type(scalar.item())

str

<h1>numpy.ndarray.astype()</h1>

In [45]:
old = np.ones((2,2)); old.dtype

dtype('float64')

In [48]:
new = np.ones((2,2)).astype('str')

In [49]:
new

array([['1.0', '1.0'],
       ['1.0', '1.0']], dtype='<U32')